# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2022 Bart Ribbers <bribbers@disroot.org>
[Desktop Entry]
Name=Plasma Remotecontrollers
Name[ar]=متحكم عن بعد لبلازما
Name[ca]=Controls remots del Plasma
Name[ca@valencia]=Controls remots del Plasma
Name[en_GB]=Plasma Remotecontrollers
Name[es]=Controladores remotos de Plasma
Name[fr]=Contrôleurs distants de Plasma
Name[hu]=Plasma távirányítók
Name[it]=Plasma Remotecontrollers
Name[ko]=Plasma 리모콘
Name[nl]=Plasma afstandsbedieningen
Name[nn]=Fjernkontrollar for Plasma
Name[pl]=Kontrolery Plazmy
Name[sl]=Plasma Remotecontrollers
Name[sv]=Plasma fjärrkontroller
Name[tr]=Plasma Uzaktan Denetimciler
Name[uk]=Дистанційне керування Плазмою
Name[x-test]=xxPlasma Remotecontrollersxx
Name[zh_CN]=Plasma 无线控制器
Description=Translates events from various input devices to native key presses
Description[ar]=يترجم الأحداث من أجهزة الإدخال المختلفة إلى كبسات مفاتيح أصلية
Description[ca]=Tradueix esdeveniments des de diversos dispositius d'entrada a pulsacions natives de tecles
Description[ca@valencia]=Tradueix esdeveniments des de diversos dispositius d'entrada a pulsacions natives de tecles
Description[en_GB]=Translates events from various input devices to native key presses
Description[es]=Traduce eventos de diversos dispositivos de entrada a pulsaciones de teclas nativas
Description[fr]=Traduit les évènements à partir de divers périphériques d'entrée en des appuis natifs de touches
Description[hu]=A különböző beviteli eszközökről érkező eseményeket lefordítása natív billentyűleütésekké
Description[it]=Traduce gli eventi da vari dispositivi di immissione in pressioni di tasti nativi
Description[ko]=다양한 입력 장치 이벤트를 키 입력으로 전환
Description[nl]=Vertaalt gebeurtenissen uit verschillende invoerapparaten naar inheemse toetsaanslagen
Description[nn]=Gjer om hendingar sende frå ulike inn-einingar om til tastetrykk
Description[pl]=Tłumaczy zdarzenia z różnych urządzeń wejściowych na naciśnięcia klawiszy
Description[ru]=Преобразование событий, получаемых с различных устройств, в нажатия клавиш
Description[sk]=Prekladá udalosti z rôznych vstupných zariadení na natívne stlačenia kláves
Description[sl]=Prevaja dogodke iz različnih vhodnih naprav v pritiske domorodnih tipk
Description[sv]=Översätter händelser från olika typer av inmatningsenheter till inbyggda tangentnedtryckningar
Description[tr]=Çeşitli girdi aygıtlarından alınan olayları yerel düğme basımlarına çevirir
Description[uk]=Транслює події з різних пристроїв введення у сигнали про натискання клавіш
Description[x-test]=xxTranslates events from various input devices to native key pressesxx
Description[zh_CN]=将各种输入设备的事件翻译为系统原生按键事件
Exec=plasma-remotecontrollers
Icon=gamepad
Type=Application
X-KDE-PluginInfo-Version=@PROJECT_VERSION@
NoDisplay=true
